//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fechas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles
    {
        public string Formato { get; set; }
        public string Descripcion { get; set; }
    
        public virtual citas citas { get; set; }
    }
}
